# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: AzureCLI@2
  displayName: Get Kubectl Credentials
  inputs:
    azureSubscription: azrm
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: az aks get-credentials --name census-k8s --resource-group Census

- task: AzureCLI@2
  displayName: Do ACR Login
  inputs:
    azureSubscription: azrm
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: az acr login --name hermanohub

- script: docker build --file ./src/microservices/People.Test.Dockerfile --tag people.test ./src/microservices
  displayName: Build Test Docker for People Microservice

- script: docker run people.test
  displayName: Test People Microservice

- script: docker build -f ./src/microservices/People.Dockerfile -t hermanohub.azurecr.io/census.people ./src/microservices
  displayName: Build Docker for People Microservice

- script: docker push hermanohub.azurecr.io/census.people
  displayName: Push Docker for People Microservice

- script: kubectl delete --ignore-not-found -f ./src/kubernetes/people.yaml && kubectl apply -f ./src/kubernetes/people.yaml
  displayName: Deploy to Kubernets Cluster
  
