apiVersion: apps/v1
kind: Deployment
metadata:
  name: census-family
spec:
  selector:
    matchLabels:
      app: census-family
  replicas: 1
  template:
    metadata:
      labels:
        app: census-family
    spec:
      containers:
      - name: census-family
        image: hermanohub.azurecr.io/census.family
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: family-service
  labels:
    app:  census-family
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: census-family