apiVersion: apps/v1
kind: Deployment
metadata:
  name: census-front
spec:
  selector:
    matchLabels:
      app: census-front
  replicas: 1
  template:
    metadata:
      labels:
        app: census-front
    spec:
      containers:
      - name: census-front
        image: hermanohub.azurecr.io/census.front
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app:  census-front
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: census-front
  type: LoadBalancer