apiVersion: apps/v1
kind: Deployment
metadata:
  name: census-people
spec:
  selector:
    matchLabels:
      app: census-people
  replicas: 1
  template:
    metadata:
      labels:
        app: census-people
    spec:
      containers:
      - name: census-people
        image: hermanohub.azurecr.io/census.people
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: people
  labels:
    app:  census-people
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: census-people